Fixed bug when checking if two ip addresses belong to the same network.
Improved output on errors adding exception throwing/catching.

Completed ebox/openvpn/server-two-clients test suite.

Now test/host-setup-script outputs scripts for all the hosts of the scenario.


git-svn-id: https://pubsvn.warp.es/anste/trunk@254 18403268-a619-4aed-af80-3a7c80afbb3a

diff --git a/src/data/common/ebox/openvpn/generate-bundle/test b/src/data/common/ebox/openvpn/generate-bundle/test
--- a/src/data/common/ebox/openvpn/generate-bundle/test
+++ b/src/data/common/ebox/openvpn/generate-bundle/test
@@ -8,11 +8,13 @@ BUNDLE=`perl $SCRIPT foobar-server $CLIENT $ROUTER`
 
 echo "Bundle generated at $BUNDLE"
 
+NEWNAME=/var/www/foobar-server-$CLIENT.tar.gz
+
 echo "Moving to /var/www ..."
-mv $BUNDLE /var/www/ || echo "Error"
+mv $BUNDLE $NEWNAME || echo "Error"
 
 
 echo "Giving read permission"
-chmod +r "/var/www/`basename $BUNDLE`" || echo "Error"
+chmod +r $NEWNAME || echo "Error"
 
-test -r "/var/www/`basename $BUNDLE`"
+test -r $NEWNAME
diff --git a/src/data/tests/ebox/openvpn/server-two-clients/start-server/test b/src/data/tests/ebox/openvpn/server-two-clients/start-server/test
--- a/src/data/tests/ebox/openvpn/server-two-clients/start-server/test
+++ b/src/data/tests/ebox/openvpn/server-two-clients/start-server/test
@@ -2,15 +2,20 @@
 
 TESTFILE=/tmp/anste-openvpn-ready-$$
 
-# FIXME: temporary workaround until fixed in ebox-openvpn
-sed -i 's/^dev unitialized/dev tap/g' foobar-server-$CLIENT.conf
+cd $CLIENT
 
-openvpn --config foobar-server-$CLIENT.conf --daemon --route-up "touch $TESTFILE" --log /tmp/$TESTFILE.log
+# FIXME: temporary workaround until fixed in ebox-openvpn
+sed -i 's/^dev unitialized/dev tap/g' foobar-server-client.conf
+
+openvpn --config foobar-server-client.conf --daemon --route-up "touch $TESTFILE" --log $TESTFILE.log
+
+OK=0
 
 for i in `seq 1 20`
 do
-    if [ -f $TESTFILE ]
+    if [ -r $TESTFILE ]
     then
+        OK=1
         echo "OpenVPN connected"
         break
     else
@@ -19,6 +24,12 @@ do
 done
 
 cat $TESTFILE.log
+
+if [ $OK == 0 ]
+then
+    echo "OpenVPN connection failed"
+    exit 1
+fi
 
 while true ; do echo foo | netcat -l -p 1100 -q 1 || exit 1 ; done &
 
